### ISSUE TITLE
Failing to parse address number correctly

### ISSUE THREAD

**Issue by JoeNVF** [datamade/usaddress#145] opened 2016-11-30 22:07 UTC
I'm trying to parse a large number of NC addresses, but some of them are failing to parse correctly.  I tried to do training using the first 7 that were improperly parsed, but it still failed again.  Issue is an address with a house number like 1234B is not getting parsed as 1234 with suffix of B.  Maybe I just did the training wrong...

Here is the XML I used to train:

`<AddressCollection>
    <AddressString>
        <AddressNumber>2419</AddressNumber>
        <AddressNumberSuffix>B</AddressNumberSuffix>
        <StreetName>GREENSBORO-CHAPEL HILL</StreetName>
        <StreetNamePreDirectional>W</StreetNamePreDirectional>
        <StreetNamePostType>RD</StreetNamePostType>
        <PlaceName>SNOW CAMP</PlaceName>
        <StateName>NC</StateName>
	<ZipCode>27349</ZipCode>
    </AddressString>
    <AddressString>
        <AddressNumber>6062</AddressNumber>
        <AddressNumberSuffix>A</AddressNumberSuffix>
	<StreetNamePreDirectional>S</StreetNamePreDirectional>
        <StreetName>NC HWY</StreetName>
	<StreetNamePostModifier>49</StreetNamePostModifier>
        <PlaceName>BURLINGTON</PlaceName>
        <StateName>NC</StateName>
	<ZipCode>27215</ZipCode>
    </AddressString>
    <AddressString>
        <AddressNumber>2933</AddressNumber>
        <AddressNumberSuffix>A</AddressNumberSuffix>
        <StreetName>ALFRED</StreetName>
        <StreetNamePostType>RD</StreetNamePostType>
        <PlaceName>GRAHAM</PlaceName>
        <StateName>NC</StateName>
	<ZipCode>27253</ZipCode>
    </AddressString>
    <AddressString>
        <AddressNumber>1711</AddressNumber>
        <AddressNumberSuffix>B</AddressNumberSuffix>
        <StreetName>DEEP CREEK CHURCH</StreetName>
        <StreetNamePostType>RD</StreetNamePostType>
        <PlaceName>BURLINGTON</PlaceName>
        <StateName>NC</StateName>
	<ZipCode>27217</ZipCode>
    </AddressString>
    <AddressString>
        <AddressNumber>4135</AddressNumber>
        <AddressNumberSuffix>A</AddressNumberSuffix>
        <StreetName>PREACHER HOLMES</StreetName>
        <StreetNamePostType>RD</StreetNamePostType>
        <PlaceName>GRAHAM</PlaceName>
        <StateName>NC</StateName>
	<ZipCode>27253</ZipCode>
    </AddressString>
    <AddressString>
        <AddressNumber>2179</AddressNumber>
        <AddressNumberSuffix>B</AddressNumberSuffix>
        <StreetName>CARL NOAH</StreetName>
        <StreetNamePostType>RD</StreetNamePostType>
        <PlaceName>SNOW CAMP</PlaceName>
        <StateName>NC</StateName>
	<ZipCode>27349</ZipCode>
    </AddressString>
    <AddressString>
        <AddressNumber>1126</AddressNumber>
        <AddressNumberSuffix>B</AddressNumberSuffix>
        <StreetName>LAWNDALE</StreetName>
        <StreetNamePostType>DR</StreetNamePostType>
        <PlaceName>GRAHAM</PlaceName>
        <StateName>NC</StateName>
	<ZipCode>27253</ZipCode>
    </AddressString>

</AddressCollection>`

**Comment by JoeNVF** [comment] 2016-12-01 07:16
To move a head in my project, for now, I just accepted address numbers with the letters in them, but found another issue.  At least one case has a bad zip code (12345 63124), haven't investigated where it got the extra numbers (and the space) yet, but wanted to add it in the issue.

**Comment by jeancochrane** [comment] 2016-12-12 22:15
Hey @JoeNVF,

Sorry for the twelve-day wait! Thanks for bearing with us.

Since address numbers can contain letters and still be valid, it's better practice for the parser to parse '1234B' as `AddressNumber` instead of dividing it into a number and a suffix. That way you'll avoid messing up valid addresses. I'd recommend that you preprocess the address number to split at suffix letters if you know they'll be in there. I added a space between the address number and the suffix in the training data you provided and the parser seemed to work fine.

RE: zip code errors – could you provide input, output, and expected behavior for cases where it failed so that I can take a look?

Happy to explain more if any of this is unclear!

**Comment by jeancochrane** [comment] 2016-12-19 22:26
Hi @JoeNVF,

It's been a week, so I'm going to close this – if you still need help with zip codes, feel free to open a new issue.

**Closed by jeancochrane** 2016-12-19 22:26 UTC
Labels: bad parse
